/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CitaSalud.pantallas;

import CitaSalud.CitaSalud;
import CitaSalud.Entidades.Cita;
import CitaSalud.Entidades.Medico;
import java.awt.event.ItemEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cesar Alegre Flores
 */
public class JPanelVisualizar extends javax.swing.JPanel {

    /**
     * Creates new form JPanelVisualizar
     */
    public JPanelVisualizar() {
        initComponents();
        inicializarComboBox();
        inicializarTabla();
    }

    private void inicializarComboBox() {
        cbMedico.removeAllItems();

        for (Medico medico : CitaSalud.medicos) {
            cbMedico.addItem(medico.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombres = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVisual = new javax.swing.JTable();
        Encabezado = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        cbMedico = new javax.swing.JComboBox<>();

        lblNombres.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblNombres.setText("FECHA:");

        txtFecha.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaKeyReleased(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 204, 204));
        btnBuscar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tbVisual.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tbVisual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "PACIENTE", "AREA", "FECHA", "HORA", "MEDICO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbVisual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbVisual.getTableHeader().setReorderingAllowed(false);
        tbVisual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVisualMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbVisual);

        Encabezado.setBackground(new java.awt.Color(27, 29, 61));

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Visualizacion");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );

        lblDni.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblDni.setText("MEDICO:");

        cbMedico.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cbMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMedico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMedicoItemStateChanged(evt);
            }
        });
        cbMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtFecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDni)
                                .addGap(110, 110, 110)
                                .addComponent(lblNombres)
                                .addGap(0, 75, Short.MAX_VALUE)))
                        .addGap(34, 34, 34)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(620, 620, 620))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(lblNombres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarTabla() {

        DefaultTableModel model = (DefaultTableModel) tbVisual.getModel();
        model.setRowCount(0);

        for (Cita cita : CitaSalud.citas) {

            if (!cita.getAtendido()) {
                Object[] fila = {
                    cita.getCodigo(),
                    cita.getPaciente().getNombre() + " " + cita.getPaciente().getApellido(),
                    cita.getArea().getNombre(),
                    cita.getFecha(),
                    cita.getHora(),
                    cita.getMedico().getNombre() + " " + cita.getMedico().getApellido()
                };
                model.addRow(fila);
            }
        }

    }

    protected void buscarFecha() {
        DefaultTableModel model = (DefaultTableModel) tbVisual.getModel();
        model.setRowCount(0);

        for (Cita nav : CitaSalud.citas) {
            if (nav.getFecha().toLowerCase().contains(txtFecha.getText().toLowerCase())) {
                Object[] fila = {
                    nav.getCodigo(),
                    nav.getPaciente().getNombre() + " " + nav.getPaciente().getApellido(),
                    nav.getArea().getNombre(),
                    nav.getFecha(),
                    nav.getHora(),
                    nav.getMedico().getNombre() + " " + nav.getMedico().getApellido()
                };
                model.addRow(fila);
            }
        }
        // Asignar el modeloTabla a tu JTable
        tbVisual.setModel(model);
    }

    private void buscarMedico() {
        DefaultTableModel model = (DefaultTableModel) tbVisual.getModel();
        model.setRowCount(0);

        for (Cita nav : CitaSalud.citas) {
            if (nav.getMedico().getNombre().toLowerCase().contains(cbMedico.getSelectedItem().toString().toLowerCase())) {
                Object[] fila = {
                    nav.getCodigo(),
                    nav.getPaciente().getNombre() + " " + nav.getPaciente().getApellido(),
                    nav.getArea().getNombre(),
                    nav.getFecha(),
                    nav.getHora(),
                    nav.getMedico().getNombre() + " " + nav.getMedico().getApellido()
                };
                model.addRow(fila);
            }
        }
    }

    protected void buscarMedicoYFecha() {
        DefaultTableModel model = (DefaultTableModel) tbVisual.getModel();
        model.setRowCount(0);

        String medicoSeleccionado = cbMedico.getSelectedItem().toString().toLowerCase();
        String fechaBuscada = txtFecha.getText().toLowerCase();

        for (Cita nav : CitaSalud.citas) {
            String nombreMedico = nav.getMedico().getNombre().toLowerCase();
            String fechaCita = nav.getFecha().toLowerCase();

            if (nombreMedico.contains(medicoSeleccionado) && fechaCita.contains(fechaBuscada)) {
                Object[] fila = {
                    nav.getCodigo(),
                    nav.getPaciente().getNombre() + " " + nav.getPaciente().getApellido(),
                    nav.getArea().getNombre(),
                    nav.getFecha(),
                    nav.getHora(),
                    nav.getMedico().getNombre() + " " + nav.getMedico().getApellido()
                };
                model.addRow(fila);
            }
        }

        // Asignar el modeloTabla a tu JTable
        tbVisual.setModel(model);
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        buscarMedicoYFecha();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tbVisualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVisualMouseClicked


    }//GEN-LAST:event_tbVisualMouseClicked

    private void txtFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyReleased

        buscarFecha();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaKeyReleased

    private void cbMedicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMedicoItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            buscarMedico();
        }

    }//GEN-LAST:event_cbMedicoItemStateChanged

    private void cbMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedicoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cbMedicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Encabezado;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbMedico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tbVisual;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
