package CitaSalud.pantallas;

import CitaSalud.CitaSalud;
import CitaSalud.Entidades.Area;
import CitaSalud.Entidades.Cita;
import CitaSalud.Entidades.Medico;
import CitaSalud.Entidades.Paciente;

/**
 *
 * @author Andres
 */
public class JFramePrincipal extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    
    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        CitaSalud.areas = Area.cargarArchivoDeTexto();
        CitaSalud.medicos = Medico.cargarArchivoDeTexto();
        CitaSalud.pacientes = Paciente.cargarArchivoDeTexto();
        CitaSalud.citas = Cita.cargarArchivoDeTexto();
        
 
        JPanelHome pHome = new JPanelHome();
        pHome.setSize(1200, 900);
        pHome.setLocation(0, 0);
        visualizarBotones();
        Ventana.removeAll();
        Ventana.add(pHome);
        Ventana.revalidate();
        Ventana.repaint();
    }
    
    private void visualizarBotones() {
        
        switch (CitaSalud.usuario.getRole()) {
            case "medico":
                btnMedico.setVisible(false);
                btnArea.setVisible(false);
                btnPaciente.setVisible(false);
                btnCita.setVisible(false);
                btnConsultorio.setVisible(true);
                btnVisualizar.setVisible(true);
                btnMedicamento.setVisible(false);
                btnCamilla.setVisible(true);
                btnSalida.setVisible(true);
                btnFarmacia.setVisible(false);
                break;
            case "asistente":
                btnMedico.setVisible(false);
                btnArea.setVisible(false);
                btnPaciente.setVisible(false);
                btnCita.setVisible(true);
                btnConsultorio.setVisible(false);
                btnVisualizar.setVisible(true);
                btnMedicamento.setVisible(false);
                btnCamilla.setVisible(false);
                btnSalida.setVisible(false);
                btnFarmacia.setVisible(true);
                break;
            case "administrador":
                btnMedico.setVisible(true);
                btnArea.setVisible(true);
                btnPaciente.setVisible(true);
                btnCita.setVisible(true);
                btnConsultorio.setVisible(true);
                btnVisualizar.setVisible(true);
                btnMedicamento.setVisible(true);
                btnCamilla.setVisible(true);
                btnSalida.setVisible(true);
                btnFarmacia.setVisible(true);
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        lblIconHome = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        btnMedico = new javax.swing.JPanel();
        lblIconMedico = new javax.swing.JLabel();
        lblMedico = new javax.swing.JLabel();
        btnArea = new javax.swing.JPanel();
        lblIconArea = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        btnPaciente = new javax.swing.JPanel();
        lblPaciente = new javax.swing.JLabel();
        lblIconPaciente = new javax.swing.JLabel();
        btnCita = new javax.swing.JPanel();
        lblIconCita = new javax.swing.JLabel();
        lblCita = new javax.swing.JLabel();
        btnConsultorio = new javax.swing.JPanel();
        lblIconConsultorio = new javax.swing.JLabel();
        lblConsultorio = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JPanel();
        lblIconHistorial = new javax.swing.JLabel();
        lblHistorial = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JPanel();
        lblConsultorio3 = new javax.swing.JLabel();
        lblIconConsultorio3 = new javax.swing.JLabel();
        btnMedicamento = new javax.swing.JPanel();
        lblIconMedicamento = new javax.swing.JLabel();
        lblMedicamento = new javax.swing.JLabel();
        btnCamilla = new javax.swing.JPanel();
        lblIconCamilla = new javax.swing.JLabel();
        lblCamilla = new javax.swing.JLabel();
        btnSalida = new javax.swing.JPanel();
        lblIconSalida = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();
        btnFarmacia = new javax.swing.JPanel();
        lblIconFarmacia = new javax.swing.JLabel();
        lblFarmacia = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        lblIconSalir = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        Ventana = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setUndecorated(true);
        setOpacity(0.98F);
        setSize(new java.awt.Dimension(1400, 900));
        getContentPane().setLayout(null);

        Menu.setBackground(new java.awt.Color(27, 29, 61));
        Menu.setAlignmentX(0.0F);
        Menu.setAlignmentY(0.0F);
        Menu.setMaximumSize(new java.awt.Dimension(235, 900));
        Menu.setMinimumSize(new java.awt.Dimension(235, 900));
        Menu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MenuMouseDragged(evt);
            }
        });
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/logo.png"))); // NOI18N
        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnHome.setBackground(new java.awt.Color(32, 34, 75));
        btnHome.setMaximumSize(new java.awt.Dimension(240, 40));
        btnHome.setMinimumSize(new java.awt.Dimension(240, 40));
        btnHome.setPreferredSize(new java.awt.Dimension(240, 40));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        lblIconHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/home32.png"))); // NOI18N
        lblIconHome.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconHome.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconHome.setPreferredSize(new java.awt.Dimension(40, 34));

        lblHome.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setText("HOME");
        lblHome.setMaximumSize(new java.awt.Dimension(190, 40));
        lblHome.setMinimumSize(new java.awt.Dimension(190, 40));
        lblHome.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblIconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnMedico.setBackground(new java.awt.Color(32, 34, 75));
        btnMedico.setMaximumSize(new java.awt.Dimension(240, 40));
        btnMedico.setMinimumSize(new java.awt.Dimension(240, 40));
        btnMedico.setPreferredSize(new java.awt.Dimension(240, 40));
        btnMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicoMouseClicked(evt);
            }
        });

        lblIconMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/medico32.png"))); // NOI18N
        lblIconMedico.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconMedico.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconMedico.setPreferredSize(new java.awt.Dimension(40, 34));

        lblMedico.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblMedico.setForeground(new java.awt.Color(255, 255, 255));
        lblMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedico.setText("MÉDICO");
        lblMedico.setMaximumSize(new java.awt.Dimension(190, 40));
        lblMedico.setMinimumSize(new java.awt.Dimension(190, 40));
        lblMedico.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout btnMedicoLayout = new javax.swing.GroupLayout(btnMedico);
        btnMedico.setLayout(btnMedicoLayout);
        btnMedicoLayout.setHorizontalGroup(
            btnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMedicoLayout.setVerticalGroup(
            btnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMedicoLayout.createSequentialGroup()
                .addGroup(btnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnArea.setBackground(new java.awt.Color(32, 34, 75));
        btnArea.setMaximumSize(new java.awt.Dimension(240, 40));
        btnArea.setMinimumSize(new java.awt.Dimension(240, 40));
        btnArea.setPreferredSize(new java.awt.Dimension(240, 40));
        btnArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAreaMouseClicked(evt);
            }
        });

        lblIconArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/area32.png"))); // NOI18N
        lblIconArea.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconArea.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconArea.setPreferredSize(new java.awt.Dimension(40, 34));

        lblArea.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArea.setText("ÁREA");
        lblArea.setMaximumSize(new java.awt.Dimension(190, 40));
        lblArea.setMinimumSize(new java.awt.Dimension(190, 40));
        lblArea.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout btnAreaLayout = new javax.swing.GroupLayout(btnArea);
        btnArea.setLayout(btnAreaLayout);
        btnAreaLayout.setHorizontalGroup(
            btnAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconArea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnAreaLayout.setVerticalGroup(
            btnAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAreaLayout.createSequentialGroup()
                .addGroup(btnAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconArea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnPaciente.setBackground(new java.awt.Color(32, 34, 75));
        btnPaciente.setMaximumSize(new java.awt.Dimension(240, 40));
        btnPaciente.setMinimumSize(new java.awt.Dimension(240, 40));
        btnPaciente.setPreferredSize(new java.awt.Dimension(240, 40));
        btnPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPacienteMouseClicked(evt);
            }
        });

        lblPaciente.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblPaciente.setForeground(new java.awt.Color(255, 255, 255));
        lblPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaciente.setText("PACIENTE");
        lblPaciente.setMaximumSize(new java.awt.Dimension(190, 40));
        lblPaciente.setMinimumSize(new java.awt.Dimension(190, 40));
        lblPaciente.setPreferredSize(new java.awt.Dimension(190, 40));

        lblIconPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/paciente32.png"))); // NOI18N
        lblIconPaciente.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconPaciente.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconPaciente.setPreferredSize(new java.awt.Dimension(40, 34));

        javax.swing.GroupLayout btnPacienteLayout = new javax.swing.GroupLayout(btnPaciente);
        btnPaciente.setLayout(btnPacienteLayout);
        btnPacienteLayout.setHorizontalGroup(
            btnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPacienteLayout.setVerticalGroup(
            btnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPacienteLayout.createSequentialGroup()
                .addGroup(btnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnCita.setBackground(new java.awt.Color(32, 34, 75));
        btnCita.setMaximumSize(new java.awt.Dimension(240, 40));
        btnCita.setMinimumSize(new java.awt.Dimension(240, 40));
        btnCita.setPreferredSize(new java.awt.Dimension(240, 40));
        btnCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCitaMouseClicked(evt);
            }
        });

        lblIconCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/cita32.png"))); // NOI18N
        lblIconCita.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconCita.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconCita.setPreferredSize(new java.awt.Dimension(40, 34));

        lblCita.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblCita.setForeground(new java.awt.Color(255, 255, 255));
        lblCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCita.setText("CITA");
        lblCita.setMaximumSize(new java.awt.Dimension(190, 40));
        lblCita.setMinimumSize(new java.awt.Dimension(190, 40));
        lblCita.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout btnCitaLayout = new javax.swing.GroupLayout(btnCita);
        btnCita.setLayout(btnCitaLayout);
        btnCitaLayout.setHorizontalGroup(
            btnCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconCita, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCita, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCitaLayout.setVerticalGroup(
            btnCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCitaLayout.createSequentialGroup()
                .addGroup(btnCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconCita, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCita, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConsultorio.setBackground(new java.awt.Color(32, 34, 75));
        btnConsultorio.setMaximumSize(new java.awt.Dimension(240, 40));
        btnConsultorio.setMinimumSize(new java.awt.Dimension(240, 40));
        btnConsultorio.setPreferredSize(new java.awt.Dimension(240, 40));
        btnConsultorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultorioMouseClicked(evt);
            }
        });

        lblIconConsultorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconConsultorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/consultorio32.png"))); // NOI18N
        lblIconConsultorio.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconConsultorio.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconConsultorio.setPreferredSize(new java.awt.Dimension(40, 34));

        lblConsultorio.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblConsultorio.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultorio.setText("CONSULTORIO");
        lblConsultorio.setMaximumSize(new java.awt.Dimension(190, 40));
        lblConsultorio.setMinimumSize(new java.awt.Dimension(190, 40));
        lblConsultorio.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout btnConsultorioLayout = new javax.swing.GroupLayout(btnConsultorio);
        btnConsultorio.setLayout(btnConsultorioLayout);
        btnConsultorioLayout.setHorizontalGroup(
            btnConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConsultorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnConsultorioLayout.setVerticalGroup(
            btnConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConsultorioLayout.createSequentialGroup()
                .addGroup(btnConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnHistorial.setBackground(new java.awt.Color(32, 34, 75));
        btnHistorial.setMaximumSize(new java.awt.Dimension(240, 40));
        btnHistorial.setMinimumSize(new java.awt.Dimension(240, 40));
        btnHistorial.setPreferredSize(new java.awt.Dimension(240, 40));
        btnHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialMouseClicked(evt);
            }
        });

        lblIconHistorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/historial32.png"))); // NOI18N
        lblIconHistorial.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconHistorial.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconHistorial.setPreferredSize(new java.awt.Dimension(40, 34));

        lblHistorial.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblHistorial.setForeground(new java.awt.Color(255, 255, 255));
        lblHistorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHistorial.setText("HISTORIAL");
        lblHistorial.setMaximumSize(new java.awt.Dimension(190, 40));
        lblHistorial.setMinimumSize(new java.awt.Dimension(190, 40));
        lblHistorial.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout btnHistorialLayout = new javax.swing.GroupLayout(btnHistorial);
        btnHistorial.setLayout(btnHistorialLayout);
        btnHistorialLayout.setHorizontalGroup(
            btnHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHistorialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnHistorialLayout.setVerticalGroup(
            btnHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHistorialLayout.createSequentialGroup()
                .addGroup(btnHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVisualizar.setBackground(new java.awt.Color(32, 34, 75));
        btnVisualizar.setMaximumSize(new java.awt.Dimension(240, 40));
        btnVisualizar.setMinimumSize(new java.awt.Dimension(240, 40));
        btnVisualizar.setPreferredSize(new java.awt.Dimension(240, 40));
        btnVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisualizarMouseClicked(evt);
            }
        });

        lblConsultorio3.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblConsultorio3.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultorio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultorio3.setText("VISUALIZACION");
        lblConsultorio3.setMaximumSize(new java.awt.Dimension(190, 40));
        lblConsultorio3.setMinimumSize(new java.awt.Dimension(190, 40));
        lblConsultorio3.setPreferredSize(new java.awt.Dimension(190, 40));

        lblIconConsultorio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconConsultorio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/visualizacion32.png"))); // NOI18N
        lblIconConsultorio3.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconConsultorio3.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconConsultorio3.setPreferredSize(new java.awt.Dimension(40, 34));

        javax.swing.GroupLayout btnVisualizarLayout = new javax.swing.GroupLayout(btnVisualizar);
        btnVisualizar.setLayout(btnVisualizarLayout);
        btnVisualizarLayout.setHorizontalGroup(
            btnVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVisualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconConsultorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConsultorio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnVisualizarLayout.setVerticalGroup(
            btnVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVisualizarLayout.createSequentialGroup()
                .addGroup(btnVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconConsultorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsultorio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMedicamento.setBackground(new java.awt.Color(32, 34, 75));
        btnMedicamento.setMaximumSize(new java.awt.Dimension(240, 40));
        btnMedicamento.setMinimumSize(new java.awt.Dimension(240, 40));
        btnMedicamento.setPreferredSize(new java.awt.Dimension(240, 40));
        btnMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicamentoMouseClicked(evt);
            }
        });

        lblIconMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/medicamento32.png"))); // NOI18N
        lblIconMedicamento.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconMedicamento.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconMedicamento.setPreferredSize(new java.awt.Dimension(40, 34));

        lblMedicamento.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblMedicamento.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicamento.setText("MEDICAMENTO");
        lblMedicamento.setMaximumSize(new java.awt.Dimension(190, 40));
        lblMedicamento.setMinimumSize(new java.awt.Dimension(190, 40));
        lblMedicamento.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout btnMedicamentoLayout = new javax.swing.GroupLayout(btnMedicamento);
        btnMedicamento.setLayout(btnMedicamentoLayout);
        btnMedicamentoLayout.setHorizontalGroup(
            btnMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMedicamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMedicamentoLayout.setVerticalGroup(
            btnMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMedicamentoLayout.createSequentialGroup()
                .addGroup(btnMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCamilla.setBackground(new java.awt.Color(32, 34, 75));
        btnCamilla.setMaximumSize(new java.awt.Dimension(240, 40));
        btnCamilla.setMinimumSize(new java.awt.Dimension(240, 40));
        btnCamilla.setPreferredSize(new java.awt.Dimension(240, 40));
        btnCamilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCamillaMouseClicked(evt);
            }
        });

        lblIconCamilla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconCamilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/camilla.png"))); // NOI18N
        lblIconCamilla.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconCamilla.setMinimumSize(new java.awt.Dimension(40, 34));

        lblCamilla.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblCamilla.setForeground(new java.awt.Color(255, 255, 255));
        lblCamilla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCamilla.setText("CAMILLA");
        lblCamilla.setMaximumSize(new java.awt.Dimension(190, 40));
        lblCamilla.setMinimumSize(new java.awt.Dimension(190, 40));
        lblCamilla.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout btnCamillaLayout = new javax.swing.GroupLayout(btnCamilla);
        btnCamilla.setLayout(btnCamillaLayout);
        btnCamillaLayout.setHorizontalGroup(
            btnCamillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCamillaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconCamilla, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCamilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCamillaLayout.setVerticalGroup(
            btnCamillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCamillaLayout.createSequentialGroup()
                .addGroup(btnCamillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCamilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconCamilla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalida.setBackground(new java.awt.Color(32, 34, 75));
        btnSalida.setMaximumSize(new java.awt.Dimension(240, 40));
        btnSalida.setMinimumSize(new java.awt.Dimension(240, 40));
        btnSalida.setPreferredSize(new java.awt.Dimension(240, 40));
        btnSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalidaMouseClicked(evt);
            }
        });

        lblIconSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/salida.png"))); // NOI18N
        lblIconSalida.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconSalida.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconSalida.setPreferredSize(new java.awt.Dimension(40, 34));

        lblSalida.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblSalida.setForeground(new java.awt.Color(255, 255, 255));
        lblSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalida.setText("SALIDA");
        lblSalida.setMaximumSize(new java.awt.Dimension(190, 40));
        lblSalida.setMinimumSize(new java.awt.Dimension(190, 40));
        lblSalida.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout btnSalidaLayout = new javax.swing.GroupLayout(btnSalida);
        btnSalida.setLayout(btnSalidaLayout);
        btnSalidaLayout.setHorizontalGroup(
            btnSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalidaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnSalidaLayout.setVerticalGroup(
            btnSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalidaLayout.createSequentialGroup()
                .addGroup(btnSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFarmacia.setBackground(new java.awt.Color(32, 34, 75));
        btnFarmacia.setMaximumSize(new java.awt.Dimension(240, 40));
        btnFarmacia.setMinimumSize(new java.awt.Dimension(240, 40));
        btnFarmacia.setPreferredSize(new java.awt.Dimension(240, 40));
        btnFarmacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFarmaciaMouseClicked(evt);
            }
        });

        lblIconFarmacia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconFarmacia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/area32.png"))); // NOI18N
        lblIconFarmacia.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconFarmacia.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconFarmacia.setPreferredSize(new java.awt.Dimension(40, 34));

        lblFarmacia.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblFarmacia.setForeground(new java.awt.Color(255, 255, 255));
        lblFarmacia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFarmacia.setText("FARMACIA");
        lblFarmacia.setMaximumSize(new java.awt.Dimension(190, 40));
        lblFarmacia.setMinimumSize(new java.awt.Dimension(190, 40));
        lblFarmacia.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout btnFarmaciaLayout = new javax.swing.GroupLayout(btnFarmacia);
        btnFarmacia.setLayout(btnFarmaciaLayout);
        btnFarmaciaLayout.setHorizontalGroup(
            btnFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFarmaciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnFarmaciaLayout.setVerticalGroup(
            btnFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFarmaciaLayout.createSequentialGroup()
                .addGroup(btnFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalir.setBackground(new java.awt.Color(32, 34, 75));
        btnSalir.setMaximumSize(new java.awt.Dimension(240, 40));
        btnSalir.setMinimumSize(new java.awt.Dimension(240, 40));
        btnSalir.setPreferredSize(new java.awt.Dimension(240, 40));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        lblIconSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/logout32.png"))); // NOI18N
        lblIconSalir.setMaximumSize(new java.awt.Dimension(40, 34));
        lblIconSalir.setMinimumSize(new java.awt.Dimension(40, 34));
        lblIconSalir.setPreferredSize(new java.awt.Dimension(40, 34));

        lblSalir.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("SALIR");
        lblSalir.setMaximumSize(new java.awt.Dimension(190, 40));
        lblSalir.setMinimumSize(new java.awt.Dimension(190, 40));
        lblSalir.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addComponent(lblIconSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addGroup(btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnMedicamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVisualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultorio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCamilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCamilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Menu);
        Menu.setBounds(0, 0, 240, 900);

        Ventana.setAlignmentX(0.0F);
        Ventana.setAlignmentY(0.0F);
        Ventana.setMaximumSize(new java.awt.Dimension(1200, 900));
        Ventana.setMinimumSize(new java.awt.Dimension(1200, 900));
        Ventana.setPreferredSize(new java.awt.Dimension(1200, 900));
        Ventana.setRequestFocusEnabled(false);
        Ventana.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Ventana);
        Ventana.setBounds(240, 0, 1200, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_MenuMousePressed

    private void MenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_MenuMouseDragged

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        JFrameLogin frameLogin = new JFrameLogin();
        frameLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCitaMouseClicked
        // TODO add your handling code here:
        JPanelCita pCita = new JPanelCita();
        pCita.setSize(1200, 900);
        pCita.setLocation(0, 0);
        
        Ventana.removeAll();
        Ventana.add(pCita);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_btnCitaMouseClicked

    private void btnPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacienteMouseClicked
        // TODO add your handling code here:
        JPanelPaciente pPaciente = new JPanelPaciente();
        pPaciente.setSize(1200, 900);
        pPaciente.setLocation(0, 0);
        
        Ventana.removeAll();
        Ventana.add(pPaciente);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_btnPacienteMouseClicked

    private void btnMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicoMouseClicked
        // TODO add your handling code here:
        JPanelMedico pMedico = new JPanelMedico();
        pMedico.setSize(1200, 900);
        pMedico.setLocation(0, 0);

        Ventana.removeAll();
        Ventana.add(pMedico);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_btnMedicoMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        JPanelHome pHome = new JPanelHome();
        pHome.setSize(1200, 900);
        pHome.setLocation(0, 0);
        
        Ventana.removeAll();
        Ventana.add(pHome);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAreaMouseClicked
        // TODO add your handling code here:
        JPanelArea pArea = new JPanelArea();
        pArea.setSize(1200, 900);
        pArea.setLocation(0, 0);
        
        Ventana.removeAll();
        Ventana.add(pArea);
        Ventana.revalidate();
        Ventana.repaint();
        
    }//GEN-LAST:event_btnAreaMouseClicked

    private void btnVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarMouseClicked
        JPanelVisualizar pVisualizar = new JPanelVisualizar();
        pVisualizar.setSize(1200, 900);
        pVisualizar.setLocation(0, 0);
        
        Ventana.removeAll();
        Ventana.add(pVisualizar);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_btnVisualizarMouseClicked

    private void btnMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicamentoMouseClicked
   
        JPanelMedicamento pMedicamento = new JPanelMedicamento();
        pMedicamento.setSize(1200, 900);
        pMedicamento.setLocation(0, 0);
        
        Ventana.removeAll();
        Ventana.add(pMedicamento);
        Ventana.revalidate();
        Ventana.repaint();
        
        
    }//GEN-LAST:event_btnMedicamentoMouseClicked

    private void btnCamillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCamillaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCamillaMouseClicked

    private void btnSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaMouseClicked

    private void btnFarmaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFarmaciaMouseClicked
        // TODO add your handling code here:
         JPanelFarmacia pFarmacia = new JPanelFarmacia();
         pFarmacia.setSize(1200, 900);
         pFarmacia.setLocation(0, 0);
        
         Ventana.removeAll();
         Ventana.add(pFarmacia);
         Ventana.revalidate();
         Ventana.repaint();
    }//GEN-LAST:event_btnFarmaciaMouseClicked

    private void btnConsultorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultorioMouseClicked
        // TODO add your handling code here:
        JPanelConsultorio pConsultorio = new JPanelConsultorio();
        pConsultorio.setSize(1200, 900);
        pConsultorio.setLocation(0, 0);
        
        Ventana.removeAll();
        Ventana.add(pConsultorio);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_btnConsultorioMouseClicked

    private void btnHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialMouseClicked
        // TODO add your handling code here:
        JPanelHistorialConsultorio pHistorial = new JPanelHistorialConsultorio();
        pHistorial.setSize(1200, 900);
        pHistorial.setLocation(0, 0);
        
        Ventana.removeAll();
        Ventana.add(pHistorial);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_btnHistorialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Ventana;
    private javax.swing.JPanel btnArea;
    private javax.swing.JPanel btnCamilla;
    private javax.swing.JPanel btnCita;
    private javax.swing.JPanel btnConsultorio;
    private javax.swing.JPanel btnFarmacia;
    private javax.swing.JPanel btnHistorial;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnMedicamento;
    private javax.swing.JPanel btnMedico;
    private javax.swing.JPanel btnPaciente;
    private javax.swing.JPanel btnSalida;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel btnVisualizar;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCamilla;
    private javax.swing.JLabel lblCita;
    private javax.swing.JLabel lblConsultorio;
    private javax.swing.JLabel lblConsultorio3;
    private javax.swing.JLabel lblFarmacia;
    private javax.swing.JLabel lblHistorial;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblIconArea;
    private javax.swing.JLabel lblIconCamilla;
    private javax.swing.JLabel lblIconCita;
    private javax.swing.JLabel lblIconConsultorio;
    private javax.swing.JLabel lblIconConsultorio3;
    private javax.swing.JLabel lblIconFarmacia;
    private javax.swing.JLabel lblIconHistorial;
    private javax.swing.JLabel lblIconHome;
    private javax.swing.JLabel lblIconMedicamento;
    private javax.swing.JLabel lblIconMedico;
    private javax.swing.JLabel lblIconPaciente;
    private javax.swing.JLabel lblIconSalida;
    private javax.swing.JLabel lblIconSalir;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel lblSalir;
    // End of variables declaration//GEN-END:variables
}
