package CitaSalud.pantallas;

import CitaSalud.CitaSalud;
import CitaSalud.Entidades.Area;
import CitaSalud.Entidades.Medico;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class JFramePrincipal extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    
    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        CitaSalud.areas = Area.cargarArchivoDeTexto();
        CitaSalud.medicos = Medico.cargarArchivoDeTexto();
        Ventana.removeAll();
        Ventana.revalidate();
        Ventana.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        lblIconHome = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        btnMedico = new javax.swing.JPanel();
        lblIconMedico = new javax.swing.JLabel();
        lblMedico = new javax.swing.JLabel();
        btnArea = new javax.swing.JPanel();
        lblIconArea = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        btnPaciente = new javax.swing.JPanel();
        lblIconPaciente = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        btnCita = new javax.swing.JPanel();
        lblIconCita = new javax.swing.JLabel();
        lblCita = new javax.swing.JLabel();
        btnConsultorio = new javax.swing.JPanel();
        lblIconConsultorio = new javax.swing.JLabel();
        lblConsultorio = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        lblIconSalir = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JPanel();
        lblConsultorio3 = new javax.swing.JLabel();
        lblIconConsultorio3 = new javax.swing.JLabel();
        btnMedicamento = new javax.swing.JPanel();
        lblIconMedicamento = new javax.swing.JLabel();
        lblMedicamento = new javax.swing.JLabel();
        btnCamilla = new javax.swing.JPanel();
        lblIconCamilla = new javax.swing.JLabel();
        lblCamilla = new javax.swing.JLabel();
        btnCamilla1 = new javax.swing.JPanel();
        lblIconCamilla1 = new javax.swing.JLabel();
        lblCamilla1 = new javax.swing.JLabel();
        Ventana = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setUndecorated(true);
        setOpacity(0.98F);
        setSize(new java.awt.Dimension(1400, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(27, 29, 61));
        Menu.setAlignmentX(0.0F);
        Menu.setAlignmentY(0.0F);
        Menu.setMaximumSize(new java.awt.Dimension(235, 900));
        Menu.setMinimumSize(new java.awt.Dimension(235, 900));
        Menu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MenuMouseDragged(evt);
            }
        });
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/logo.png"))); // NOI18N

        btnHome.setBackground(new java.awt.Color(32, 34, 75));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        lblIconHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/home32.png"))); // NOI18N

        lblHome.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setText("HOME");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addComponent(lblIconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMedico.setBackground(new java.awt.Color(32, 34, 75));
        btnMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicoMouseClicked(evt);
            }
        });

        lblIconMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/medico32.png"))); // NOI18N

        lblMedico.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblMedico.setForeground(new java.awt.Color(255, 255, 255));
        lblMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedico.setText("MÉDICO");

        javax.swing.GroupLayout btnMedicoLayout = new javax.swing.GroupLayout(btnMedico);
        btnMedico.setLayout(btnMedicoLayout);
        btnMedicoLayout.setHorizontalGroup(
            btnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMedicoLayout.createSequentialGroup()
                .addComponent(lblIconMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMedicoLayout.setVerticalGroup(
            btnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnArea.setBackground(new java.awt.Color(32, 34, 75));
        btnArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAreaMouseClicked(evt);
            }
        });

        lblIconArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/area32.png"))); // NOI18N

        lblArea.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArea.setText("ÁREA");

        javax.swing.GroupLayout btnAreaLayout = new javax.swing.GroupLayout(btnArea);
        btnArea.setLayout(btnAreaLayout);
        btnAreaLayout.setHorizontalGroup(
            btnAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAreaLayout.createSequentialGroup()
                .addComponent(lblIconArea, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAreaLayout.setVerticalGroup(
            btnAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPaciente.setBackground(new java.awt.Color(32, 34, 75));
        btnPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPacienteMouseClicked(evt);
            }
        });

        lblIconPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/paciente32.png"))); // NOI18N

        lblPaciente.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblPaciente.setForeground(new java.awt.Color(255, 255, 255));
        lblPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaciente.setText("PACIENTE");

        javax.swing.GroupLayout btnPacienteLayout = new javax.swing.GroupLayout(btnPaciente);
        btnPaciente.setLayout(btnPacienteLayout);
        btnPacienteLayout.setHorizontalGroup(
            btnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPacienteLayout.createSequentialGroup()
                .addComponent(lblIconPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPacienteLayout.setVerticalGroup(
            btnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCita.setBackground(new java.awt.Color(32, 34, 75));
        btnCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCitaMouseClicked(evt);
            }
        });

        lblIconCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/cita32.png"))); // NOI18N

        lblCita.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblCita.setForeground(new java.awt.Color(255, 255, 255));
        lblCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCita.setText("CITA");

        javax.swing.GroupLayout btnCitaLayout = new javax.swing.GroupLayout(btnCita);
        btnCita.setLayout(btnCitaLayout);
        btnCitaLayout.setHorizontalGroup(
            btnCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCitaLayout.createSequentialGroup()
                .addComponent(lblIconCita, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnCitaLayout.setVerticalGroup(
            btnCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConsultorio.setBackground(new java.awt.Color(32, 34, 75));

        lblIconConsultorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconConsultorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/consultorio32.png"))); // NOI18N

        lblConsultorio.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblConsultorio.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultorio.setText("CONSULTORIO");

        javax.swing.GroupLayout btnConsultorioLayout = new javax.swing.GroupLayout(btnConsultorio);
        btnConsultorio.setLayout(btnConsultorioLayout);
        btnConsultorioLayout.setHorizontalGroup(
            btnConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConsultorioLayout.createSequentialGroup()
                .addComponent(lblIconConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConsultorio, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        );
        btnConsultorioLayout.setVerticalGroup(
            btnConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConsultorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconConsultorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConsultorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalir.setBackground(new java.awt.Color(32, 34, 75));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        lblIconSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/logout32.png"))); // NOI18N

        lblSalir.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("SALIR");

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addComponent(lblIconSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVisualizar.setBackground(new java.awt.Color(32, 34, 75));
        btnVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisualizarMouseClicked(evt);
            }
        });

        lblConsultorio3.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblConsultorio3.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultorio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultorio3.setText("VISUALIZACION");

        lblIconConsultorio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconConsultorio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/buscar48.png"))); // NOI18N

        javax.swing.GroupLayout btnVisualizarLayout = new javax.swing.GroupLayout(btnVisualizar);
        btnVisualizar.setLayout(btnVisualizarLayout);
        btnVisualizarLayout.setHorizontalGroup(
            btnVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVisualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconConsultorio3)
                .addGap(18, 18, 18)
                .addComponent(lblConsultorio3)
                .addContainerGap())
        );
        btnVisualizarLayout.setVerticalGroup(
            btnVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVisualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconConsultorio3)
                    .addComponent(lblConsultorio3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMedicamento.setBackground(new java.awt.Color(32, 34, 75));
        btnMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicamentoMouseClicked(evt);
            }
        });

        lblIconMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/medicamento32.png"))); // NOI18N

        lblMedicamento.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblMedicamento.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicamento.setText("MEDICAMENTO");

        javax.swing.GroupLayout btnMedicamentoLayout = new javax.swing.GroupLayout(btnMedicamento);
        btnMedicamento.setLayout(btnMedicamentoLayout);
        btnMedicamentoLayout.setHorizontalGroup(
            btnMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMedicamentoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblIconMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        );
        btnMedicamentoLayout.setVerticalGroup(
            btnMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMedicamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCamilla.setBackground(new java.awt.Color(32, 34, 75));
        btnCamilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCamillaMouseClicked(evt);
            }
        });

        lblIconCamilla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconCamilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/camilla.png"))); // NOI18N

        lblCamilla.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblCamilla.setForeground(new java.awt.Color(255, 255, 255));
        lblCamilla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCamilla.setText("CAMILLA");

        javax.swing.GroupLayout btnCamillaLayout = new javax.swing.GroupLayout(btnCamilla);
        btnCamilla.setLayout(btnCamillaLayout);
        btnCamillaLayout.setHorizontalGroup(
            btnCamillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCamillaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblIconCamilla, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCamilla, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        btnCamillaLayout.setVerticalGroup(
            btnCamillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCamillaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnCamillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconCamilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCamilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCamilla1.setBackground(new java.awt.Color(32, 34, 75));
        btnCamilla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCamilla1MouseClicked(evt);
            }
        });

        lblIconCamilla1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconCamilla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/salida.png"))); // NOI18N

        lblCamilla1.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblCamilla1.setForeground(new java.awt.Color(255, 255, 255));
        lblCamilla1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCamilla1.setText("SALIDA");

        javax.swing.GroupLayout btnCamilla1Layout = new javax.swing.GroupLayout(btnCamilla1);
        btnCamilla1.setLayout(btnCamilla1Layout);
        btnCamilla1Layout.setHorizontalGroup(
            btnCamilla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCamilla1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblIconCamilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCamilla1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        btnCamilla1Layout.setVerticalGroup(
            btnCamilla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCamilla1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnCamilla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconCamilla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCamilla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConsultorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnVisualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMedicamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCamilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCamilla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblLogo)
                .addGap(41, 41, 41)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCamilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCamilla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 900));

        Ventana.setAlignmentX(0.0F);
        Ventana.setAlignmentY(0.0F);
        Ventana.setMaximumSize(new java.awt.Dimension(1200, 900));
        Ventana.setMinimumSize(new java.awt.Dimension(1200, 900));
        Ventana.setPreferredSize(new java.awt.Dimension(1200, 900));
        Ventana.setRequestFocusEnabled(false);
        Ventana.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1200, 900));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_MenuMousePressed

    private void MenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_MenuMouseDragged

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCitaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCitaMouseClicked

    private void btnPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPacienteMouseClicked

    private void btnMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicoMouseClicked
        // TODO add your handling code here:
        JPanelMedico pMedico = new JPanelMedico();
        pMedico.setSize(1200, 900);
        pMedico.setLocation(0, 0);

        Ventana.removeAll();
        Ventana.add(pMedico);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_btnMedicoMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        Ventana.removeAll();
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAreaMouseClicked
        // TODO add your handling code here:
        JPanelArea pArea = new JPanelArea();
        pArea.setSize(1200, 900);
        pArea.setLocation(0, 0);
        
        Ventana.removeAll();
        Ventana.add(pArea);
        Ventana.revalidate();
        Ventana.repaint();
        
    }//GEN-LAST:event_btnAreaMouseClicked

    private void btnVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarMouseClicked
        JPanelVisualizar pVisualizar = new JPanelVisualizar();
        pVisualizar.setSize(1200, 900);
        pVisualizar.setLocation(0, 0);
        
        Ventana.removeAll();
        Ventana.add(pVisualizar);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_btnVisualizarMouseClicked

    private void btnMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicamentoMouseClicked
   
        JPanelMedicamento pMedicamento = new JPanelMedicamento();
        pMedicamento.setSize(1200, 900);
        pMedicamento.setLocation(0, 0);
        
        Ventana.removeAll();
        Ventana.add(pMedicamento);
        Ventana.revalidate();
        Ventana.repaint();
        
        
    }//GEN-LAST:event_btnMedicamentoMouseClicked

    private void btnCamillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCamillaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCamillaMouseClicked

    private void btnCamilla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCamilla1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCamilla1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Ventana;
    private javax.swing.JPanel btnArea;
    private javax.swing.JPanel btnCamilla;
    private javax.swing.JPanel btnCamilla1;
    private javax.swing.JPanel btnCita;
    private javax.swing.JPanel btnConsultorio;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnMedicamento;
    private javax.swing.JPanel btnMedico;
    private javax.swing.JPanel btnPaciente;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel btnVisualizar;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCamilla;
    private javax.swing.JLabel lblCamilla1;
    private javax.swing.JLabel lblCita;
    private javax.swing.JLabel lblConsultorio;
    private javax.swing.JLabel lblConsultorio3;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblIconArea;
    private javax.swing.JLabel lblIconCamilla;
    private javax.swing.JLabel lblIconCamilla1;
    private javax.swing.JLabel lblIconCita;
    private javax.swing.JLabel lblIconConsultorio;
    private javax.swing.JLabel lblIconConsultorio3;
    private javax.swing.JLabel lblIconHome;
    private javax.swing.JLabel lblIconMedicamento;
    private javax.swing.JLabel lblIconMedico;
    private javax.swing.JLabel lblIconPaciente;
    private javax.swing.JLabel lblIconSalir;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblSalir;
    // End of variables declaration//GEN-END:variables
}
