package CitaSalud.pantallas;

import CitaSalud.CitaSalud;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Andres
 */
public class JPanelHome extends javax.swing.JPanel {

    private final Timer timer; // Timer para actualizar la hora cada segundo

    /**
     * Creates new form JPanelHome
     */
    public JPanelHome() {
        initComponents();
        lblRolValor.setText(CitaSalud.usuario.getRole());
        lblUsernameValor.setText(CitaSalud.usuario.getUsername());
                
        Date fechaActual = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("EEEE, d 'de' MMMM 'de' yyyy");
        String fechaFormateada = formatoFecha.format(fechaActual);
        lblFecha.setText(fechaFormateada);

        actualizarHora();

        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actualizarHora();
            }
        });

        timer.start();
    }

    private void actualizarHora() {
        Date horaActual = new Date();
        SimpleDateFormat formatoHora = new SimpleDateFormat("hh:mm:ss a");
        String horaFormateada = formatoHora.format(horaActual);
        lblHora.setText(horaFormateada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblRolValor = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblUsernameValor = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1200, 900));
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setPreferredSize(new java.awt.Dimension(1200, 900));
        setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        lblTitulo.setText("Bienvenido a CitaSalud");
        add(lblTitulo);
        lblTitulo.setBounds(190, 90, 910, 87);

        lblRol.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblRol.setText("rol:");
        add(lblRol);
        lblRol.setBounds(510, 310, 52, 45);

        lblRolValor.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblRolValor.setText("{rol}");
        add(lblRolValor);
        lblRolValor.setBounds(600, 310, 390, 45);

        lblUsername.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblUsername.setText("username:");
        add(lblUsername);
        lblUsername.setBounds(380, 390, 190, 45);

        lblUsernameValor.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblUsernameValor.setText("{username}");
        add(lblUsernameValor);
        lblUsernameValor.setBounds(600, 390, 480, 45);

        lblFecha.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblFecha.setText("[EEEE, d 'de' MMMM 'de' yyyy]");
        add(lblFecha);
        lblFecha.setBounds(370, 640, 520, 45);

        lblHora.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblHora.setText("[hh:mm:ss tt]");
        add(lblHora);
        lblHora.setBounds(520, 700, 220, 45);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblRolValor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsernameValor;
    // End of variables declaration//GEN-END:variables
}
