package CitaSalud.pantallas;

import CitaSalud.Entidades.Paciente;
import CitaSalud.CitaSalud;
import static CitaSalud.CitaSalud.citas;
import CitaSalud.Entidades.Area;
import CitaSalud.Entidades.Cita;
import CitaSalud.Entidades.Medico;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres
 */
public class JPanelCita extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCita
     */
    public JPanelCita() {
        initComponents();
        limpiarControles();
        inicializarCbPaciente();
        inicializarCbArea();
        inicializarCbMedico();
        inicializarTabla();
    }
    
    private void inicializarCbPaciente() {
        cbPaciente.removeAllItems();
        for (Paciente paciente : CitaSalud.pacientes) {
            
            cbPaciente.addItem(paciente.getNombre() + " " + paciente.getApellido());
        }
    }
    
    private void inicializarCbArea() {
        cbArea.removeAllItems();
        for (Area area : CitaSalud.areas) {
            
            cbArea.addItem(area.getNombre());
        }
    }
    
    private void inicializarCbMedico() {
        cbMedico.removeAllItems();
        for (Medico medico : CitaSalud.medicos) {
            
            if (cbArea.getSelectedItem().equals(medico.getArea().get(0).getNombre())){
                cbMedico.addItem(medico.getNombre() + " " + medico.getApellido());
            }
        }
    }
    
    private void inicializarTabla() {
        
        DefaultTableModel model = (DefaultTableModel) tbCita.getModel();
        model.setRowCount(0);
        
        for (Cita cita : CitaSalud.citas) {
            
            if (!cita.getAtendido()) {
                Object[] fila = { 
                    cita.getCodigo(), 
                    cita.getPaciente().getNombre() + " " + cita.getPaciente().getApellido(),
                    cita.getArea().getNombre(),
                    cita.getFecha(),
                    cita.getHora(),
                    cita.getMedico().getNombre() + " " + cita.getMedico().getApellido()
                };
                model.addRow(fila);
            }
        }
    }
    
    private void limpiarControles() {
        
        if (!CitaSalud.citas.isEmpty()) {
            Cita ultimaCita = CitaSalud.citas.get(CitaSalud.citas.size() - 1);
            String ultimoCodigo = ultimaCita.getCodigo();
            int numero = Integer.parseInt(ultimoCodigo.substring(1)) + 1;
            String nuevoCodigo = "C" + String.format("%07d", numero);
            txtCodigo.setText(nuevoCodigo);
        } else {
            txtCodigo.setText("C0000001");
        }
        
        txtCodigo.setEditable(false);
        txtFecha.setText("dd/MM/yyyy");
        txtHora.setText("HH:mm");
    }
    
    private void buscarItemComboBox(JComboBox<String> cbNombre, String buscar) {
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) cbNombre.getModel();

        // Buscar el indice del texto deseado
        int index = -1;
        for (int i = 0; i < model.getSize(); i++) {
            String item = model.getElementAt(i);
            if (item.equals(buscar)) {
                index = i;
                break;
            }
        }

        // Establecer el indice como seleccionado:
        if (index != -1) {
            cbNombre.setSelectedIndex(index);
        }
    }
    
    private boolean existeCita(String codigo) {
        for (Cita cita : CitaSalud.citas) {
            if (cita.getCodigo().equals(codigo)) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Encabezado = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblPaciente = new javax.swing.JLabel();
        cbPaciente = new javax.swing.JComboBox<>();
        lblArea = new javax.swing.JLabel();
        cbArea = new javax.swing.JComboBox<>();
        lblMedico = new javax.swing.JLabel();
        cbMedico = new javax.swing.JComboBox<>();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCita = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();
        lblIconBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1200, 900));
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setPreferredSize(new java.awt.Dimension(1200, 900));

        Encabezado.setBackground(new java.awt.Color(27, 29, 61));

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CITA");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblCodigo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCodigo.setText("CODIGO:");

        txtCodigo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        lblPaciente.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblPaciente.setText("PACIENTE:");

        cbPaciente.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        lblArea.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblArea.setText("ÁREA");

        cbArea.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cbArea.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAreaItemStateChanged(evt);
            }
        });

        lblMedico.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblMedico.setText("MÉDICO:");

        cbMedico.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        lblFecha.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblFecha.setText("FECHA:");

        txtFecha.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtFecha.setText("dd/MM/yyyy");

        lblHora.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblHora.setText("HORA:");

        txtHora.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtHora.setText("HH:mm");

        btnRegistrar.setBackground(new java.awt.Color(153, 255, 153));
        btnRegistrar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 204, 204));
        btnEliminar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tbCita.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tbCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "PACIENTE", "AREA", "FECHA", "HORA", "MÉDICO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbCita.getTableHeader().setReorderingAllowed(false);
        tbCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCita);

        btnImprimir.setBackground(new java.awt.Color(255, 255, 51));
        btnImprimir.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        lblIconBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CitaSalud/Imagenes/buscar32.png"))); // NOI18N

        txtBuscar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCodigo)
                                        .addComponent(cbMedico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMedico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbPaciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHora)
                                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(276, 276, 276))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(342, 342, 342))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(193, 193, 193)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(lblPaciente)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblArea)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMedico)
                            .addComponent(lblHora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addGap(37, 37, 37)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnEliminar)
                    .addComponent(btnImprimir))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        Cita nuevaCita = new Cita();
        
        if (!CitaSalud.citas.isEmpty()) {
            Cita ultimaCita = CitaSalud.citas.get(CitaSalud.citas.size() - 1);
            String ultimoCodigo = ultimaCita.getCodigo();
            int numero = Integer.parseInt(ultimoCodigo.substring(1)) + 1;
            String nuevoCodigo = "C" + String.format("%07d", numero);
            nuevaCita.setCodigo(nuevoCodigo);
        } else {
            nuevaCita.setCodigo("C0000001");
        }
        
        for (Paciente paciente : CitaSalud.pacientes) {
            if ((paciente.getNombre() + " " + paciente.getApellido())
                    .equals(cbPaciente.getSelectedItem())) {
                nuevaCita.setPaciente(paciente);
                break;
            }
        }
        
        for (Area area : CitaSalud.areas) {
            if (area.getNombre()
                    .equals(cbArea.getSelectedItem())) {
                nuevaCita.setArea(area);
                break;
            }
        }

        for (Medico medico : CitaSalud.medicos) {
            if ((medico.getNombre() + " " + medico.getApellido())
                    .equals(cbMedico.getSelectedItem())) {
                nuevaCita.setMedico(medico);
                break;
            }
        }
        
        nuevaCita.setFecha(txtFecha.getText());
        nuevaCita.setHora(txtHora.getText());
        
        if (nuevaCita.validarFormatoFecha()) {
            if (nuevaCita.validarFormatoHora()){
                CitaSalud.citas.add(nuevaCita);
                Cita.actualizar(citas);
                inicializarTabla();
                limpiarControles();
                return;
            }
            JOptionPane.showMessageDialog(null, "El formato de fecha es incorrecto.", "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(null, "El formato de hora es incorrecto.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        return;
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        String codigo = txtCodigo.getText();
        
        if (existeCita(codigo)) {
            int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar esta cita?", "Confirmación", JOptionPane.YES_NO_OPTION);
            
            if (opcion == JOptionPane.YES_OPTION) {
                for (Cita cita : CitaSalud.citas) {
                    if (cita.getCodigo().equals(codigo)) {
                        CitaSalud.citas.remove(cita);
                        break;
                    }
                }
                Cita.actualizar(citas);
                inicializarTabla();
                limpiarControles();
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la cita", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tbCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCitaMouseClicked
        
        int filaSeleccionada = tbCita.getSelectedRow();
        
        if (filaSeleccionada != -1) {
            Object valor = tbCita.getValueAt(filaSeleccionada, 0);
            
            for (Cita cita : CitaSalud.citas) {
                if (cita.getCodigo().equals(valor)) {
                    
                    txtCodigo.setText(cita.getCodigo());
                    
                    buscarItemComboBox(cbPaciente, cita.getPaciente().getNombre() + " " + cita.getPaciente().getApellido());
                    buscarItemComboBox(cbArea, cita.getArea().getNombre());
                    buscarItemComboBox(cbMedico, cita.getMedico().getNombre() + " " + cita.getMedico().getApellido());
                    
                    txtFecha.setText(cita.getFecha());
                    txtHora.setText(cita.getHora());
                }
            }
        }
    }//GEN-LAST:event_tbCitaMouseClicked

    private void cbAreaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAreaItemStateChanged
        cbMedico.removeAllItems();
        for (Medico medico : CitaSalud.medicos) {
            
            if (cbArea.getSelectedItem().equals(medico.getArea().get(0).getNombre())){
                cbMedico.addItem(medico.getNombre() + " " + medico.getApellido());
            }
        }
    }//GEN-LAST:event_cbAreaItemStateChanged

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        JFrameImprimir pImprimir = new JFrameImprimir();
        pImprimir.setVisible(true);
        pImprimir.setSize(424, 660);
        pImprimir.setLocation(0, 0);
        

// TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        if (txtBuscar.getText().isEmpty()) {
            inicializarTabla();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tbCita.getModel();
        model.setRowCount(0);

        for (Cita cita : CitaSalud.citas) {
            
            String nombres = cita.getPaciente().getNombre() + " " 
                    + cita.getPaciente().getApellido();
            
            if (!cita.getAtendido() && 
                    nombres.toLowerCase().contains(txtBuscar.getText())) {
                Object[] fila = { 
                    cita.getCodigo(), 
                    cita.getPaciente().getNombre() + " " + cita.getPaciente().getApellido(),
                    cita.getArea().getNombre(),
                    cita.getFecha(),
                    cita.getHora(),
                    cita.getMedico().getNombre() + " " + cita.getMedico().getApellido()
                };
                model.addRow(fila);
            }
        }
    }//GEN-LAST:event_txtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Encabezado;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbArea;
    private javax.swing.JComboBox<String> cbMedico;
    private javax.swing.JComboBox<String> cbPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIconBuscar;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tbCita;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
